import { createI18n } from 'vue-i18n'
import type { SupportedLanguage } from '../types/citizenship'

const base = {
  appName: 'Staatsklar', subtitle: 'Einbürgerungstest Trainer', home: 'Übersicht', study: 'Lernen', plan: '7-Tage-Plan', test: 'Prüfung', mistakes: 'Fehler', favorites: 'Favoriten', stats: 'Statistik', settings: 'Einstellungen',
  welcome: 'Bereit für deinen Einbürgerungstest?', heroCopy: 'Lerne strukturiert, übe gezielt und gehe sicher in die Prüfung.', startStudy: 'Lernen starten', startTest: 'Prüfung starten', continue: 'Weiterlernen', allQuestions: 'Alle Fragen', chooseState: 'Nach Bundesland lernen', reviewMistakes: 'Fehler wiederholen', progress: 'Fortschritt', answered: 'Beantwortet', accuracy: 'Trefferquote', streak: 'Tagesstreak', today: 'Heute', questions: 'Fragen', question: 'Frage', previous: 'Zurück', next: 'Weiter', check: 'Antwort prüfen', correct: 'Richtig', incorrect: 'Nicht richtig', explanation: 'Die richtige Antwort ist', favorite: 'Zu Favoriten', removeFavorite: 'Aus Favoriten entfernen', submit: 'Prüfung abgeben', newTest: 'Neue Prüfung', result: 'Prüfungsergebnis', passed: 'Bestanden', failed: 'Noch üben', score: 'Punktzahl', wrong: 'Falsch', unanswered: 'Offen', time: 'Zeit', category: 'Kategorie', noMistakes: 'Noch keine Fehler. Stark!', noFavorites: 'Noch keine Favoriten gespeichert.', selectState: 'Bundesland auswählen', system: 'System', light: 'Hell', dark: 'Dunkel', export: 'Daten exportieren', import: 'Daten importieren', reset: 'Alles zurücksetzen', resetConfirm: 'Wirklich alle Fortschritte löschen?', language: 'Sprache', theme: 'Darstellung', dailyGoal: 'Dein Lernziel', weakCategories: 'Schwache Kategorien', practice: 'Üben', completed: 'abgeschlossen', review: 'Antworten ansehen', tests: 'Prüfungen', passRate: 'Bestehensquote', highest: 'Bestes Ergebnis', average: 'Durchschnitt', selectAnswer: 'Wähle eine Antwort', stateQuestions: 'Fragen mit allgemeinen und landesbezogenen Inhalten', day: 'Tag', of: 'von', activeTest: 'Prüfung läuft', testWarning: 'Du hast unbeantwortete Fragen.'
}

const translations: Record<SupportedLanguage, Record<string, string>> = Object.fromEntries(
  (['de', 'en', 'fa', 'ar', 'tr', 'fr', 'es', 'it', 'ru', 'uk', 'pl', 'pt', 'zh', 'ja'] as SupportedLanguage[]).map((language) => [language, base])
) as Record<SupportedLanguage, Record<string, string>>
translations.en = { ...base, appName: 'CivicPrep', subtitle: 'Citizenship Test Trainer', home: 'Overview', study: 'Study', plan: '7-day plan', test: 'Test', mistakes: 'Mistakes', favorites: 'Favorites', stats: 'Statistics', settings: 'Settings', welcome: 'Ready for your citizenship test?', heroCopy: 'Learn with structure, practice with focus, and walk into the exam prepared.', startStudy: 'Start studying', startTest: 'Start test', continue: 'Continue learning', allQuestions: 'All questions', chooseState: 'Study by state', reviewMistakes: 'Review mistakes', answered: 'Answered', accuracy: 'Accuracy', streak: 'Day streak', today: 'Today', questions: 'questions', question: 'Question', previous: 'Previous', next: 'Next', check: 'Check answer', correct: 'Correct', incorrect: 'Incorrect', explanation: 'The correct answer is', favorite: 'Add to favorites', removeFavorite: 'Remove favorite', submit: 'Submit test', newTest: 'New test', result: 'Test result', passed: 'Passed', failed: 'Keep practicing', score: 'Score', wrong: 'Wrong', unanswered: 'Unanswered', time: 'Time', noMistakes: 'No mistakes yet. Strong work!', noFavorites: 'No favorites saved yet.', selectState: 'Choose a state', export: 'Export data', import: 'Import data', reset: 'Reset everything', language: 'Language', theme: 'Appearance', system: 'System', light: 'Light', dark: 'Dark', weakCategories: 'Weak categories', practice: 'Practice', completed: 'completed', review: 'Review answers', tests: 'Tests', passRate: 'Pass rate', highest: 'Highest score', average: 'Average', selectAnswer: 'Choose an answer', stateQuestions: 'General and state-specific questions', day: 'Day', of: 'of', activeTest: 'Test in progress', testWarning: 'You have unanswered questions.' }
translations.fa = { ...base, appName: 'آمادگی شهروندی', subtitle: 'تمرین آزمون تابعیت آلمان', home: 'نمای کلی', study: 'مطالعه', plan: 'برنامه ۷ روزه', test: 'آزمون', mistakes: 'اشتباهات', favorites: 'نشان‌شده‌ها', stats: 'آمار', settings: 'تنظیمات', welcome: 'برای آزمون تابعیت آماده‌ای؟', heroCopy: 'با برنامه یاد بگیر، هدفمند تمرین کن و با اطمینان وارد آزمون شو.', startStudy: 'شروع مطالعه', startTest: 'شروع آزمون', continue: 'ادامه یادگیری', allQuestions: 'همه پرسش‌ها', chooseState: 'مطالعه بر اساس ایالت', reviewMistakes: 'مرور اشتباهات', answered: 'پاسخ داده‌شده', accuracy: 'دقت', streak: 'توالی روزانه', today: 'امروز', questions: 'پرسش', question: 'پرسش', previous: 'قبلی', next: 'بعدی', check: 'بررسی پاسخ', correct: 'درست', incorrect: 'نادرست', favorite: 'افزودن به نشان‌شده‌ها', removeFavorite: 'حذف از نشان‌شده‌ها', submit: 'تحویل آزمون', newTest: 'آزمون جدید', result: 'نتیجه آزمون', passed: 'قبول شدید', failed: 'نیاز به تمرین بیشتر', score: 'امتیاز', wrong: 'غلط', unanswered: 'بی‌پاسخ', time: 'زمان', noMistakes: 'هنوز اشتباهی ثبت نشده است.', noFavorites: 'هنوز پرسش نشان‌شده‌ای ندارید.', selectState: 'انتخاب ایالت', export: 'خروجی گرفتن', import: 'وارد کردن داده', reset: 'بازنشانی همه', language: 'زبان', theme: 'ظاهر', system: 'سیستم', light: 'روشن', dark: 'تیره', weakCategories: 'دسته‌های ضعیف', practice: 'تمرین', completed: 'تکمیل شده', review: 'مرور پاسخ‌ها', tests: 'آزمون‌ها', passRate: 'نرخ قبولی', highest: 'بهترین امتیاز', average: 'میانگین', day: 'روز', of: 'از' }
translations.ar = { ...translations.fa, appName: 'استعد للمواطنة', subtitle: 'تدريب اختبار التجنّس', home: 'نظرة عامة', study: 'تعلّم', test: 'اختبار', settings: 'الإعدادات', startStudy: 'ابدأ التعلّم', startTest: 'ابدأ الاختبار', next: 'التالي', previous: 'السابق' }

export const languageOptions: { code: SupportedLanguage; label: string; rtl?: boolean }[] = [
  { code: 'de', label: 'Deutsch' }, { code: 'en', label: 'English' }, { code: 'fa', label: 'فارسی', rtl: true }, { code: 'ar', label: 'العربية', rtl: true }, { code: 'tr', label: 'Türkçe' }, { code: 'fr', label: 'Français' }, { code: 'es', label: 'Español' }, { code: 'it', label: 'Italiano' }, { code: 'ru', label: 'Русский' }, { code: 'uk', label: 'Українська' }, { code: 'pl', label: 'Polski' }, { code: 'pt', label: 'Português' }, { code: 'zh', label: '中文' }, { code: 'ja', label: '日本語' }
]

export default createI18n({ legacy: false, locale: 'de', fallbackLocale: 'de', messages: translations })
